# Data loading

In [9]:
df =  pd.read_csv(r'D:\Data analyst\datasets_kaggle\Uber_Data_Analytics_Dashboard\ncr_ride_bookings.csv')

# Libraries importing

In [ ]:
import pandas as pd

# Data types, statistics and null values

In [10]:
print('ðŸ“Œ Data info:')
df.info()

print('\nðŸ“Š Statistics')
print(df.describe(include = 'all'))

print('\nðŸ“‹ Null values per column')
print(df.isnull().sum())

ðŸ“Œ Data info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 21 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Date                               150000 non-null  object
 1   Time                               150000 non-null  object
 2   Booking ID                         150000 non-null  object
 3   Booking Status                     150000 non-null  object
 4   Customer ID                        150000 non-null  object
 5   Vehicle Type                       150000 non-null  object
 6   Pickup Location                    150000 non-null  object
 7   Drop Location                      150000 non-null  object
 8   Avg VTAT                           139500 non-null  float64
 9   Avg CTAT                           102000 non-null  float64
 10  Cancelled Rides by Customer        10500 non-null   float64
 11  Reason for cancelling by Customer  10500 non-null   object
 12  Cancelled Rides by Driver          27000 non-null   float64
 13  Driver Cancellation Reason         27000 non-null   object
 14  Incomplete Rides                   9000 non-null    float64
 15  Incomplete Rides Reason            9000 non-null    object
 16  Booking Value                      102000 non-null  float64
 17  Ride Distance                      102000 non-null  float64
 18  Driver Ratings                     93000 non-null   float64
 19  Customer Rating                    93000 non-null   float64
 20  Payment Method                     102000 non-null  object
dtypes: float64(9), object(12)
memory usage: 24.0+ MB

ðŸ“Š Statistics
              Date      Time    Booking ID Booking Status   Customer ID  \
count       150000    150000        150000         150000        150000
unique         365     62910        148767              5        148788
top     2024-11-16  17:44:57  "CNR3648267"      Completed  "CID6715450"
freq           462        16             3          93000             3
mean           NaN       NaN           NaN            NaN           NaN
std            NaN       NaN           NaN            NaN           NaN
min            NaN       NaN           NaN            NaN           NaN
25%            NaN       NaN           NaN            NaN           NaN
50%            NaN       NaN           NaN            NaN           NaN
75%            NaN       NaN           NaN            NaN           NaN
max            NaN       NaN           NaN            NaN           NaN

       Vehicle Type Pickup Location Drop Location       Avg VTAT  \
count        150000          150000        150000  139500.000000
unique            7             176           176            NaN
top            Auto         Khandsa        Ashram            NaN
freq          37419             949           936            NaN
mean            NaN             NaN           NaN       8.456352
std             NaN             NaN           NaN       3.773564
min             NaN             NaN           NaN       2.000000
25%             NaN             NaN           NaN       5.300000
50%             NaN             NaN           NaN       8.300000
75%             NaN             NaN           NaN      11.300000
max             NaN             NaN           NaN      20.000000

             Avg CTAT  ...  Reason for cancelling by Customer  \
count   102000.000000  ...                              10500
unique            NaN  ...                                  5
top               NaN  ...                      Wrong Address
freq              NaN  ...                               2362
mean        29.149636  ...                                NaN
std          8.902577  ...                                NaN
min         10.000000  ...                                NaN
25%         21.600000  ...                                NaN
50%         28.800000  ...                                NaN
75%         36.800000  ...                                NaN
max         45.000000  ...                                NaN

       Cancelled Rides by Driver  Driver Cancellation Reason Incomplete Rides  \
count                    27000.0                       27000           9000.0
unique                       NaN                           4              NaN
top                          NaN      Customer related issue              NaN
freq                         NaN                        6837              NaN
mean                         1.0                         NaN              1.0
std                          0.0                         NaN              0.0
min                          1.0                         NaN              1.0
25%                          1.0                         NaN              1.0
50%                          1.0                         NaN              1.0
75%                          1.0                         NaN              1.0
max                          1.0                         NaN              1.0

        Incomplete Rides Reason  Booking Value  Ride Distance  Driver Ratings  \
count                      9000  102000.000000  102000.000000    93000.000000
unique                        3            NaN            NaN             NaN
top             Customer Demand            NaN            NaN             NaN
freq                       3040            NaN            NaN             NaN
mean                        NaN     508.295912      24.637012        4.230992
std                         NaN     395.805774      14.002138        0.436871
min                         NaN      50.000000       1.000000        3.000000
25%                         NaN     234.000000      12.460000        4.100000
50%                         NaN     414.000000      23.720000        4.300000
75%                         NaN     689.000000      36.820000        4.600000
max                         NaN    4277.000000      50.000000        5.000000

        Customer Rating  Payment Method
count      93000.000000          102000
unique              NaN               5
top                 NaN             UPI
freq                NaN           45909
mean           4.404584             NaN
std            0.437819             NaN
min            3.000000             NaN
25%            4.200000             NaN
50%            4.500000             NaN
75%            4.800000             NaN
max            5.000000             NaN

[11 rows x 21 columns]

ðŸ“‹ Null values per column
Date                                      0
Time                                      0
Booking ID                                0
Booking Status                            0
Customer ID                               0
Vehicle Type                              0
Pickup Location                           0
Drop Location                             0
Avg VTAT                              10500
Avg CTAT                              48000
Cancelled Rides by Customer          139500
Reason for cancelling by Customer    139500
Cancelled Rides by Driver            123000
Driver Cancellation Reason           123000
Incomplete Rides                     141000
Incomplete Rides Reason              141000
Booking Value                         48000
Ride Distance                         48000
Driver Ratings                        57000
Customer Rating                       57000
Payment Method                        48000
dtype: int64

In [14]:
new_cols = []

for col in df.columns:
    fixed_cols = col.replace(' ','_').lower()
    new_cols.append(fixed_cols)

df.columns = new_cols

df.columns

Index(['date', 'time', 'booking_id', 'booking_status', 'customer_id',
       'vehicle_type', 'pickup_location', 'drop_location', 'avg_vtat',
       'avg_ctat', 'cancelled_rides_by_customer',
       'reason_for_cancelling_by_customer', 'cancelled_rides_by_driver',
       'driver_cancellation_reason', 'incomplete_rides',
       'incomplete_rides_reason', 'booking_value', 'ride_distance',
       'driver_ratings', 'customer_rating', 'payment_method'],
      dtype='object')

## Timestamp processing

In [17]:
df['date'] = pd.to_datetime(df['date'], errors='coerce')
df['time'] = pd.to_datetime(df['time'], format='%H:%M:%S', errors ='coerce').dt.time

df['datetime'] = pd.to_datetime(df['date'].astype(str) + ' ' + df['time'].astype(str), errors='coerce')

df['hour'] = df['datetime'].dt.hour
df['day'] = df['datetime'].dt.day
df['month'] = df['datetime'].dt.month
df['weekday'] = df['datetime'].dt.dayofweek
df['is_weekend'] = df['weekday'].isin([5,6])

df.head()

,date,time,booking_id,booking_status,customer_id,vehicle_type,pickup_location,drop_location,avg_vtat,avg_ctat,...,ride_distance,driver_ratings,customer_rating,payment_method,datetime,hour,day,month,weekday,is_weekend
0,2024-03-23,12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,NaN,NaN,...,NaN,NaN,NaN,NaN,2024-03-23 12:29:38,12,23,3,5,True
1,2024-11-29,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,...,5.73,NaN,NaN,UPI,2024-11-29 18:01:39,18,29,11,4,False
2,2024-08-23,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,...,13.58,4.9,4.9,Debit Card,2024-08-23 08:56:10,8,23,8,4,False
3,2024-10-21,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,...,34.02,4.6,5.0,UPI,2024-10-21 17:17:25,17,21,10,0,False
4,2024-09-16,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,...,48.21,4.1,4.3,UPI,2024-09-16 22:08:00,22,16,9,0,False